### ISSUE TITLE
Add a import task in case of first install

### ISSUE THREAD

**Issue by jmchantrein** [supertarto/ansible-grr#1]
Hello,

In case of first install of GRR, table "tables.my.sql" is not import. I suggest you to add a task and a variable like this in your tasks/main.yml after task "Deploy tables.my.sql (UTF8)":

```yml
- name: Import tables.my.sql in case of first install
  community.mysql.mysql_db:
    name: "{{ grr_db_name }}"
    state: import
    target: "{{ grr_content_dest }}/installation/tables.my.sql"
    force: yes
  when: grr_first_install
  tags: import_bdd

```

and in default/main.yml:

```yml
grr_first_install: false # False to prevent override existing database
```

Anyway, thank you for your work.

Regards.
